server:
  port: 8080

spring:
  datasource:
    username: root
    password: Mrf12345
    url: jdbc:mysql://maruifu.cn:3306/wechat?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
